let keyMirror = require("keymirror");

let APIRoot = "http://192.168.1.9";

module.exports = {

 APIEndPoints : {
    TOKEN: APIRoot + "/token",
    GET_LUPS : APIRoot + "/api/publicLups",
    GET_LUP_ENTRIES: APIRoot + "/api/entries/",
     GET_LUP_ENTIRES_PUBLIC: APIRoot + "/api/publicentries/",
     LATEST_LUP_ENTRIES: APIRoot + "/api/latestentries",
     LATEST_PUBLIC_LUP_ENTRIES: APIRoot + "/api/latestpublicentries",
     LUPR_CHECK: APIRoot + "/api/luprcheck",
     LUPR_LUPS: APIRoot + "/api/lupr/lups",
     VALIDATE_TITLE: APIRoot + "/api/lup/entry/validateTitle/",
     SAVEPOST: APIRoot + '/api/entry',
     VALIDATENAME: APIRoot + "/api/lupr/checkname",
     REGISTER: APIRoot + "/api/lupr/Register",
     STATES: APIRoot + "/api/states",
     CITIES: APIRoot + "/api/cities",
     TAGS: APIRoot + "/api/Tags",
     SAVELUP: APIRoot + "/api/lup/create",
     LOGOUT: APIRoot + "/api/Account/Logout",
     ARCHIVE: APIRoot + "/api/lup/archive/",
     DELETEENTRY: APIRoot + "/api/entry/",
     UPDATEPOST: APIRoot + "/api/entry/",
     JOINLUP: APIRoot + "/api/lup/join/",
     COMMENT: APIRoot + "/api/comments/",
     SAVECAMERAIMAGE: APIRoot + "/api/userimage/save/",
     SAVEDRAFT: APIRoot + "/api/draft/",


 },
  PayloadSources: keyMirror({
    SERVER_ACTION: null,
    VIEW_ACTION: null,
    REQUEST_ACTION:null
  }),
  ActionTypes:keyMirror({
      LUPSLOADING: null,
      LUPSLOADED: null,
      LUPLOADING: null,
      LUPLOADED: null,
      LOGIN: null,
      LOGGEDIN: null,
      LOGGEDINERROR: null,
      USERREGISTERING: null,
      USERREGISTERED: null,
      USERREGISTERERROR: null,
      SAVINGPOST: null,
      POSTSAVED: null,
      POSTSAVEDERROR: null,
      LUPRCHECKSUCCESS: null,
      LUPRCHECKFAILED: null,
      NAMEOK: null,
      NAMEERROR: null,
      STATESLOADED: null,
      CITIESLOADED: null,
      TAGSLOADED: null,
      LUPSAVED: null,
      LUPSAVEDERROR: null,
      POSTTITLEGOOD: null,
      POSTTITLEBAD: null,
      LOGOUT: null,
      ARCHIVINGLUP: null,
      LUPARCHIVED: null,
      LUPARCHIVEDFAILED: null,
      DELETINGENTRY: null,
      ENTRYDELETED: null,
      ENTRYDELETEDFAILED: null,
      JOINLUP: null,
      LUPJOINED: null,
      LUPJOINEDERROR: null,
      SENDINVITEREQUEST: null,
      SENDINVITEREQUESTSUCCESS: null,
      SENDINVITEREQIESTERROR: null,
      SAVECOMMENT: null,
      SAVECOMMENTSUCCESS: null,
      SAVECOMMENTFAILED: null,
      DELETECOMMENT: null,
      DELETECOMMENTSUCCESS: null,
      DELETECOMMENTFAILED: null,
      LUPLOADEDFAILED: null,
      SAVEDRAFT: null,
      SAVEDRAFTSUCCESS: null,
      SAVEDRAFTFAILED: null,
      GETDRAFTS: null,
      GETDRAFTSSUCCESS: null,
      GETDRAFTSFAILED: null,


  })

};
